// next/src/pages/[id].tsx
import { useRouter } from 'next/router'
import { useQuery } from 'urql'
import { GetPost, GetPostQuery, GetPostQueryVariables } from '~/generated/graphql'

function PostShow() {
  const router = useRouter()

  const [result] = useQuery<GetPostQuery, GetPostQueryVariables>({
    query: GetPost,
    variables: { id: router.query.id as string },
  })

  return (
    <div>
      <h1 className="text-center text-4xl font-extrabold">{result.data?.post?.title}</h1>
      <div className="border rounded p-4 mt-4">
        <p>{result?.data?.post.body}</p>
      </div>
    </div>
  )
}

export default PostShow

// web/src/routes/[id].svelte
<script lang="ts">
  import { page } from '$app/stores'
  import { GetPost } from '$lib/generated/graphql'
  import type { GetPostQuery, GetPostQueryVariables } from '$lib/generated/graphql'
  import { onMount } from 'svelte'

  let post: GetPostQuery['post'] | undefined = undefined
  onMount(async () => {
    const { client } = await import('$lib/modules/apollo')

    const { data } = await client.query<GetPostQuery, GetPostQueryVariables>({
      query: GetPost,
      variables: { id: $page.params.id },
    })
    post = data.post
  })
</script>

<h1 class="text-center text-4xl font-extrabold">{post?.title}</h1>
<div class="border rounded p-4 mt-4">
  <p>{post?.body}</p>
</div>
